import "./App.css";
import React, { useEffect, useState } from "react";
import axios from "axios";

function App() {
  const [Post, setPost] = useState([]);
  const hosturl = "https://gorest.co.in/public/v2/";
  const token =
    "a73b7eea017b4090a3b23cd07029bf4abe747d81e401bd5ab25a0f2a6429a8a9";
  const headers = {
    "Content-Type": "application/json",
    Authorization: `Bearer ${token}`,
  };
  const postitems = Post.map((listitem) => (
    <tr>
      <td>{listitem.id}</td>
      <td>{listitem.user_id}</td>
      <td>{listitem.title}</td>
      <td>{listitem.body}</td>
      <td>
        <button onClick={() => editpost(listitem)}>Edit</button>
      </td>
      <td>
        <button onClick={() => deletepost(listitem.id)}>Delete</button>
      </td>
     
    </tr>
  ));
  const [postPost, newPost] = useState({
    id: "",
    user_id: "",
    title: "",
    body: "",
  });

  useEffect(() => {
    getPost().then((data) => setPost(data.data));
  }, []);

  const getPost = () => {
    return axios.get(`${hosturl}posts`, { headers });
  };

  const addPost = () => {
    console.log(postPost);
    return axios.post(`${hosturl}posts`, postPost, { headers });
  };

  const deletepost = (id) => {
    console.log(id);
    return axios.delete(`${hosturl}posts/${id}`, { headers });
  };

  const editpost = (listitem) => {
    console.log(listitem);
    newPost(listitem);
  };
  const updatePost = () => {
    return axios.put(`${hosturl}posts/${postPost.id}`, postPost, { headers });
  };

  return (
    <div>
       <input
        placeholder="id (autogenerated)"
        value={postPost.id}
        onChange={(e) => newPost({ ...postPost, id: e.target.value })}
        readOnly
      />
      <input
        placeholder="user_id"
        value={postPost.user_id}
        onChange={(e) => newPost({ ...postPost, user_id: e.target.value })}
      />
      <input
        placeholder="title"
        value={postPost.title}
        onChange={(e) => newPost({ ...postPost, title: e.target.value })}
      />
      <input
        placeholder="body"
        value={postPost.body}
        onChange={(e) => newPost({ ...postPost, body: e.target.value })}
      />
      <br />
      <button onClick={addPost}>CREATE</button>
      <button onClick={updatePost}>Update</button>
      <br />
      <br />
      <table>
        <caption></caption>
        <tr>
          <th>ID</th>
          <th>USER_ID</th>
          <th>TITLE</th>
          <th>BODY</th>
        </tr>
        {postitems}
      </table>
    </div>
  );
}

export default App;
